### ISSUE TITLE
'BraintreeCore.h' file not found

### ISSUE THREAD

**Issue by Bob-MYMC** [ekreative/react-native-braintree#19]
```
▸ Compiling react-native-braintree-dummy.m
▸ Compiling RNBraintreeApplePay.m
▸ Compiling RNBraintree.m

❌  /Users/boblin/Desktop/WorkSpace/ReactNative/ignite/moon/node_modules/@ekreative/react-native-braintree/ios/RNBraintree.m:2:9: 'BraintreeCore.h' file not found

#import "BraintreeCore.h"
```

## environment
```
    "react": "18.0.0",
    "react-native": "0.69.6",
    "@ekreative/react-native-braintree": "^1.3.0",
```

**Comment by JonPekkonen** [comment]
I'm having this same issue.
@Bob-MYMC Did you manage to resolve issue?

**Comment by vasylnahuliak** [comment]
Did you install pods?
@Bob-MYMC @JonPekkonen

**Comment by JonPekkonen** [comment]
> Did you install pods?

Yes.
I'm trying to make build with eas which uses fastlane for compiling. Project used to compile and work perfectly fine but after adding this package build fails to following error.

```
› Compiling @ekreative/react-native-braintree Pods/react-native-braintree » react-native-braintree-dummy.m
› Compiling @ekreative/react-native-braintree Pods/react-native-braintree » RNBraintreeApplePay.m
› Compiling @ekreative/react-native-braintree Pods/react-native-braintree » RNBraintree.m

❌  (node_modules/@ekreative/react-native-braintree/ios/RNBraintree.m:2:9)

  1 | #import "RNBraintree.h"
> 2 | #import "BraintreeCore.h"
    |         ^ 'BraintreeCore.h' file not found
  3 | #import "BTCardClient.h"
  4 | #import "BraintreePayPal.h"
  5 | #import "BTDataCollector.h"
```

**Comment by vasylnahuliak** [comment]
This library does not support at Expo. Please, try on the CLI project.

**Comment by Bob-MYMC** [comment]
the issue can be solved by adding Braintree to the local Podfile
```
  pod 'Braintree'
  pod 'Braintree/Core'
```

**Comment by vasylnahuliak** [comment]
> he issue can be solved by adding Braintree to the local Podfile

You can avoid these changes because library supported autolinking

https://github.com/ekreative/react-native-braintree/blob/master/react-native-braintree.podspec#L27

**Comment by Ravi-Nagarro07** [comment]
I am having the same issue.
Anyone able to solve this issue?

**Comment by vasylnahuliak** [comment]
> I am having the same issue.
> Anyone able to solve this issue?

Please provide some information about your project (`npx react-native info`)

**Comment by Ravi-Nagarro07** [comment]
> > I am having the same issue.
> > Anyone able to solve this issue?
> 
> Please provide some information about your project (`npx react-native info`)

@vasylnahuliak 

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 103.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by vasylnahuliak** [comment]
@Ravi-Nagarro07 could you try to init project on 0.69 version of React Native

**Comment by Ravi-Nagarro07** [comment]
@vasylnahuliak 
Same error on version 0.69.0 as well.

**Comment by vasylnahuliak** [comment]
> @vasylnahuliak Same error on version 0.69.0 as well.

Did you use Expo?
Did you install pods?
Did you see Braintree in the Podfile.lock file?
Did you try using https://www.npmjs.com/package/react-native-clean-project for a clean cache?
Did you clean the Derived Data? https://stackoverflow.com/a/41039886/10617148

**Comment by Ravi-Nagarro07** [comment]
@vasylnahuliak 
Using react-native Cli
I do have installed pods
Braintree is available in podfile.lock file
Yes, I have tried cleaning the cache and derived data as well.

**Comment by vasylnahuliak** [comment]
> the issue can be solved by adding Braintree to the local Podfile
> 
> ```
>   pod 'Braintree'
>   pod 'Braintree/Core'
> ```

Did you try this hack?

**Comment by Ravi-Nagarro07** [comment]
> > the issue can be solved by adding Braintree to the local Podfile
> > ```
> >   pod 'Braintree'
> >   pod 'Braintree/Core'
> > ```
> 
> Did you try this hack?

This hack is not working for me.

**Comment by Ravi-Nagarro07** [comment]
> > > the issue can be solved by adding Braintree to the local Podfile
> > > ```
> > >   pod 'Braintree'
> > >   pod 'Braintree/Core'
> > > ```
> > 
> > 
> > Did you try this hack?
> 
> This hack is not working for me.

@vasylnahuliak 
check podfile and package.json

<img width="1056" alt="Screenshot 2023-01-09 at 6 04 13 PM" src="https://user-images.githubusercontent.com/102012981/211309151-2747d8a8-02e2-4398-b690-fc314724ba42.png">
<img width="1056" alt="Screenshot 2023-01-09 at 6 03 39 PM" src="https://user-images.githubusercontent.com/102012981/211309165-3f3a89ba-a4f4-4c1a-b031-512aa4d6cb7c.png">

**Comment by vasylnahuliak** [comment]
> check podfile and package.json

looks good

**Comment by Ravi-Nagarro07** [comment]
> > check podfile and package.json
> 
> looks good

but issue is still there.

**Comment by Ravi-Nagarro07** [comment]
Its working for react-native version 0.67.0.

**Comment by vasylnahuliak** [comment]
> Its working for react-native version 0.67.0.

In my case working for react-native version 0.69.7

**Comment by rahim-chopdawg** [comment]
is any one solve this issue i still facing this this

**Comment by vasylnahuliak** [comment]
Fixed in https://github.com/ekreative/react-native-braintree/pull/25
