### ISSUE TITLE
Post the UI of the plugin in the git description.

### ISSUE THREAD

**Issue by ehtisham-ali-emumba** [ekreative/react-native-braintree#21]
Can someone please post the UI of this plugin in the readme desc, so we could know it without installing it?

**Comment by vasylnahuliak** [comment]
This library doesn't have any UI. Read more about Custom UI https://www.braintreepayments.com/features/seamless-checkout/custom-ui

If you need to use UI you can install this library https://github.com/ekreative/react-native-braintree-payments-drop-in Read more about Drop-in UI https://developer.paypal.com/braintree/docs/start/drop-in

**Comment by ehtisham-ali-emumba** [comment]
@vasylnahuliak makes sense, thanks for coming here quickly.
I have one more question here, this plugin seems up to date and very good but how come this plugin is not providing Braintree DropIn functionality, is this on the way, or are any plans for it?

**Comment by vasylnahuliak** [comment]
@ehtisham-ali-emumba No

> If you need to use UI you can install this library https://github.com/ekreative/react-native-braintree-payments-drop-in Read more about Drop-in UI https://developer.paypal.com/braintree/docs/start/drop-in
