### ISSUE TITLE
BrainTree/Apple uses deprecated fields

### ISSUE THREAD

**Issue by ehtisham-ali-emumba** [ekreative/react-native-braintree#22]
I believe this package is using an old version for Braintree/Apple which has some deprecated fields in it and that is crashing on ios. 
I tested on a bareflow latest react native project (0.70.6) and I am having the below error, can someone guide me?

![Screenshot 2022-12-13 at 3 01 13 PM](https://user-images.githubusercontent.com/85542150/207287990-8233e2f2-fbd9-45df-9e8e-9076f8d0147d.png)

**Comment by vasylnahuliak** [comment]
Please try on the clean project with React Native v0.69

**Comment by ehtisham-ali-emumba** [comment]
@vasylnahuliak I am on the latest react native version, can you tell me when this plugin will be compliant with the latest rn version bcz currently, I had to do some tweaks on ios side inside this package to run it on my local.

**Comment by vasylnahuliak** [comment]
>  I had to do some tweaks on ios side inside this package to run it on my local.

Please share your changes using [patch-package](https://www.npmjs.com/package/patch-package) for other users

**Comment by vasylnahuliak** [comment]
> can you tell me when this plugin will be compliant with the latest rn version 

This library is supported for the internal project. Now we do not have any plan for upgrading react-native.

Approximate estimate: 0.5 - 1 year

**Comment by ehtisham-ali-emumba** [comment]
cool @vasylnahuliak I will, thanks.

**Comment by vasylnahuliak** [comment]
Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please feel free to create a new issue with up-to-date information.
