### ISSUE TITLE
Error: PayPal is not enabled. See https://developers.braintreepayments.com/guides/paypal/overview/android/

### ISSUE THREAD

**Issue by patrickleemsantos** [ekreative/react-native-braintree#23]

**Comment by vasylnahuliak** [comment]
@patrickleemsantos  Please provide details information:
- version of the package
- version of react-native
- is the Expo project?
- provide the minimal code for reproducing

**Comment by patrickleemsantos** [comment]
> @patrickleemsantos Please provide details information:
> 
> * version of the package
> * version of react-native
> * is the Expo project?
> * provide the minimal code for reproducing

version of the package: 1.4.0
version of react-native: 0.63.4
is the Expo project?: No
provide the minimal code for reproducing: 

  RNBraintree.showPayPalModule({
            clientToken:
                '<access token>',
            amount: '10',
            currencyCode: 'USD',
        })
            .then(result => console.log('RESULT', result))
            .catch(error => console.log('ERROR', error));

I already activated paypal on braintree and do a linking but still receiving that error.

**Comment by patrickleemsantos** [comment]
I found out that the token being used was incorrect. I will now close this ticket.
