### ISSUE TITLE
Error in the run3DSecureCheck function

### ISSUE THREAD

**Issue by Benetzz** [ekreative/react-native-braintree#24]
Hi all, 
while executing the run3DSecureCheck function, we got this error:

`[Error: {"error":{"message":"Record not found"},"fieldErrors":[]}]`

How to reproduce it: 
- just try with the example on the docs
- OS: Android API target 31

```

RNBraintree.run3DSecureCheck({
    clientToken: 'CLIENT_TOKEN_GENERATED_ON_SERVER_SIDE', -> we replaced the clientToken here
    nonce: 'CARD_NONCE',
    amount: '122.00',
    email: 'email@mail.com',
    firstname: '',
    lastname: '',
    phoneNumber: '',
    streetAddress: '',
    streetAddress2: '',
    city: '',
    region: '',
    postalCode: '',
    countryCode: ''
    })
    .then(result => console.log(result))
    .catch((error) => console.log(error));
```

**Comment by vasylnahuliak** [comment]
Please provide some information about your project (npx react-native info)

**Comment by vasylnahuliak** [comment]
Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please feel free to create a new issue with up-to-date information.
