### ISSUE TITLE
Google Play Error: SDK: Braintree Payments com.braintreepayments.api:data-collector (consider upgrading to version 4.31.0) 

### ISSUE THREAD

**Issue by ShahKhalid808** [ekreative/react-native-braintree#35]
Hi,

We are using the latest version of the @ekreative/react-native-braintree in our app. I recently submitted a build of an app to Google Play Store. The app got rejected giving the following reason:

**Issue found: Violation of User Data policy

We reviewed SDKs used by your app and found noncompliant version(s) of SDK(s) which collects persistent device identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers.

Issue details

We found an issue in the following area(s):

SPLIT_BUNDLE 28: :
SDK: Braintree Payments com.braintreepayments.api:data-collector (consider upgrading to version 4.31.0)

Additionally, follow these steps to bring your app into compliance:

You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK.**

I've been submitting builds for this app for the last 18 months without issue until this week where it's been rejected. The User Data Policy on Google Play store had been updated recently.

Is there any way to upgrade the plugin to use version 4.31.0 of com.braintreepayments.api:data-collector as suggested?

Thanks

**Comment by vasylnahuliak** [comment]
You can try to set the version for your project in `android/app/build.gradle`

```java
dependencies {
  // your deps
  implementation 'com.braintreepayments.api:data-collector:4.31.0'
}
```

**Comment by ShahKhalid808** [comment]
@vasylnahuliak I try this solution but  didn't work for me. can you try to fixe this issue as soon as possible.

**Comment by vasylnahuliak** [comment]
I created a special branch with a bumped version of data-collector https://github.com/ekreative/react-native-braintree/commit/d300550c664e02667e70f915113817c2e3e1b345

You could install the package from GitHub using certain commit 

```sh
npm i https://github.com/ekreative/react-native-braintree#d300550
```

**Comment by ShahKhalid808** [comment]
still getting the same issue for android and now it is also not working on ios giving error 'BraintreeThreeDSecure.h' file not found on ios

**Comment by vasylnahuliak** [comment]
> still getting the same issue for android

We do not yet get this error for our applications. We need more time to investigate. It is hard to reproduce.

> also not working on ios giving error 'BraintreeThreeDSecure.h' file not found on ios

This is strange because I didn't make any changes for iOS.

I will try to release these changes. There can be some effect for installing from GitHub or npm.

**Comment by vasylnahuliak** [comment]
@ShahKhalid808 please update the latest version from npm https://www.npmjs.com/package/@ekreative/react-native-braintree?activeTab=versions

```sh
npm install @ekreative/react-native-braintree@latest
```

**Comment by ShahKhalid808** [comment]
after updating the library to  latest version. I got below issue on pod install 
1. react-native version : 0.68.2
2. @ekreative/react-native-braintree": "^2.2.0"

[!] CocoaPods could not find compatible versions for pod "Braintree/ApplePay":
  In Podfile:
    react-native-braintree (from `../node_modules/@ekreative/react-native-braintree`) was resolved to 2.2.0, which depends on
      Braintree/ApplePay

There are only pre-release versions available satisfying the following requirements:

        'Braintree/ApplePay', '>= 0'

You should explicitly specify the version in order to install a pre-release version

**Comment by ShahKhalid808** [comment]
for android i'm getting still the same issue from play store.

Version code 44: :
SDK: Braintree Payments com.braintreepayments.api:data-collector (consider upgrading to version 4.31.0)

only this libray is using com.braintreepayments.api:data-collector in my project and that is also updated but still i'm getting the above issue on android

**Comment by vasylnahuliak** [comment]
> after updating the library to latest version. I got below issue on pod install

The v2.2.0 version didn't have any changes for iOS. This issue is only for your setup. Try to clean your project https://www.npmjs.com/package/react-native-clean-project Feel free to return to the previous version to reproduce this issue.

**Comment by vasylnahuliak** [comment]
> Version code 44: :
> SDK: Braintree Payments com.braintreepayments.api:data-collector (consider upgrading to version 4.31.0)

Do you use CI for deployment to Google Play?

Please attach a list of Android dependencies using these commands:

```sh
cd android
./gradlew app:dependencies  
```

https://github.com/braintree/braintree-android-drop-in/issues/373#issuecomment-1333808906

<details>
  <summary>v2.2.0</summary>

```groovy
 +--- com.braintreepayments.api:three-d-secure:4.38.0
 |    +--- com.braintreepayments.api:braintree-core:4.38.0 (*)
 |    +--- com.braintreepayments.api:card:4.38.0 (*)
 |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10 -> 1.7.22 (*)
 |    +--- org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-4
 |    +--- androidx.appcompat:appcompat:1.3.1 -> 1.4.1 (*)
 |    \--- androidx.lifecycle:lifecycle-runtime:2.3.0 -> 2.4.0 (*)
```

</details>

<details>
  <summary>v2.1.0</summary>

```groovy
 +--- com.braintreepayments.api:three-d-secure:4.27.2
 |    +--- com.braintreepayments.api:braintree-core:4.27.2 (*)
 |    +--- com.braintreepayments.api:card:4.27.2 (*)
 |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.32 -> 1.7.22 (*)
 |    +--- org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2
 |    +--- androidx.appcompat:appcompat:1.3.1 -> 1.4.1 (*)
 |    \--- androidx.lifecycle:lifecycle-runtime:2.3.0 -> 2.4.0 (*)
```

</details>

**Comment by vasylnahuliak** [comment]
Also, you can try this workaround https://github.com/pikaju/flutter-braintree/issues/129#issuecomment-1333743059 for @ekreative/react-native-braintree v2.1.0 which you do not have troubles with iOS

```groovy
implementation('com.braintreepayments.api:three-d-secure:4.27.2){
      exclude group: "org.jfrog.cardinalcommerce.gradle", module: "cardinalmobilesdk"
}
implementation("org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2")
```

**Comment by vasylnahuliak** [comment]
Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please feel free to create a new issue with up-to-date information.
