### ISSUE TITLE
Add Ukrainian README

### ISSUE THREAD

**Issue by vasylnahuliak** [ekreative/react-native-braintree#39]
🇺🇦

**Comment by IrkenStudio** [comment]
Hi I would like to take on this assignment

**Comment by vasylnahuliak** [comment]
Will be good somebody take participating in this issue for review.

Feel free to leave comments in PR

**Comment by Hollister009** [comment]
I will take a look into this PR

**Comment by Hollister009** [comment]
Hey @IrkenStudio I added the new section to README.md, please consider translating it as well:
https://github.com/ekreative/react-native-braintree/pull/64
