### ISSUE TITLE
Error: undeclared identifier 'BTAppSwitch'

### ISSUE THREAD

**Issue by Seanmclem** [ekreative/react-native-braintree#4]
hi, when using BTAppSwitch in my AppDelegate.m, I am getting `undeclared identifier 'BTAppSwitch'`, and build fails.

Did I miss a step?

**Comment by vasylnahuliak** [comment]
@Seanmclem  Can you provide code from `AppDelegate.m`
For example https://github.com/ekreative/react-native-braintree#ios-specific

**Comment by Seanmclem** [comment]
> @Seanmclem Can you provide code from `AppDelegate.m`
> For example https://github.com/ekreative/react-native-braintree#ios-specific

Hi, it looks something like this 

```objectivec AppDelegate.m
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [BTAppSwitch setReturnURLScheme:@"com.mycompany.myapp.payments"];
  //...
}

```

I've tried importing things from Braintree but they didn't seem to make a difference. So I have nothing from Braintree imported into AppDelegate.m..

Here's more detail 

```objectivec

#import "AppDelegate.h"
#import <Firebase.h>
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>

#import <UMCore/UMModuleRegistry.h>
#import <UMReactNativeAdapter/UMNativeModulesProxy.h>
#import <UMReactNativeAdapter/UMModuleRegistryAdapter.h>
#import <EXSplashScreen/EXSplashScreenService.h>
#import <UMCore/UMModuleRegistryProvider.h>

#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@interface AppDelegate () <RCTBridgeDelegate>

@property (nonatomic, strong) UMModuleRegistryAdapter *moduleRegistryAdapter;
@property (nonatomic, strong) NSDictionary *launchOptions;

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  [BTAppSwitch setReturnURLScheme:@"com.your-company-name.your-app-name.payments"]; // ADD THIS LINE
// ^^ undeclared identifier 'BTAppSwitch'


    if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
  InitializeFlipper(application);
#endif
  
  self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]];
  self.launchOptions = launchOptions;
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  #ifdef DEBUG
    [self initializeReactNativeApp];
  #else
    EXUpdatesAppController *controller = [EXUpdatesAppController sharedInstance];
    controller.delegate = self;
    [controller startAndShowLaunchScreen:self.window];
  #endif

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
}
```

**Comment by vasylnahuliak** [comment]
I don't see `#import "BraintreeCore.h"` in your import, example in https://github.com/ekreative/react-native-braintree#update-your-code (first line)

**Comment by vasylnahuliak** [comment]
> I've tried importing things from Braintree but they didn't seem to make a difference. So I have nothing from Braintree imported into AppDelegate.m..

You must add `#import "BraintreeCore.h"` in top file, see about your error here
https://learnappmaking.com/unresolved-identifier-understanding-xcode/

Are you run `pod install` in ios folder your project?

**Comment by Seanmclem** [comment]
> > I've tried importing things from Braintree but they didn't seem to make a difference. So I have nothing from Braintree imported into AppDelegate.m..
> 
> You must add `#import "BraintreeCore.h"` in top file, see about your error here
> https://learnappmaking.com/unresolved-identifier-understanding-xcode/
> 
> Are you run `pod install` in ios folder your project?
> 
> 

Even though all my imports use < brackets > so far, it's OK to use "quotes"? 

Yes I have run pod install. Should I try "pod clean" then install again? Anything like that?

**Comment by vasylnahuliak** [comment]
> Even though all my imports use < brackets > so far, it's OK to use "quotes"?

It's ok, because you use quotes in first line code `#import "AppDelegate.h"`

> Should I try "pod clean" then install again? Anything like that?

You can try clean pods folder. Or better run `npx react-native-clean-project` https://github.com/pmadruga/react-native-clean-project

**Comment by Seanmclem** [comment]
Thanks. Are there any downsides to cleaning? Like will it clear anything I might need that I can't undo?

**Comment by vasylnahuliak** [comment]
> Are there any downsides to cleaning?

I using this package when I catch strange bugs. This help me a lot.

> Like will it clear anything I might need that I can't undo?

Please set this question in library issue https://github.com/pmadruga/react-native-clean-project/issues/new

**Comment by Seanmclem** [comment]
@vasylnahuliak My issue was that I needed to specifically import `#import "BraintreeCore.h"` in my `AppDelegate.m` _before_ a set of `FB_SONARKIT_ENABLED` conditions. I was just putting it at the end of my imports which was after that. Moving it above those imports immediately mitigated my issue. 

Example

```objectivec
#import "AppDelegate.h"
#import <Firebase.h>
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>

#import <UMCore/UMModuleRegistry.h>
#import <UMReactNativeAdapter/UMNativeModulesProxy.h>
#import <UMReactNativeAdapter/UMModuleRegistryAdapter.h>
#import <EXSplashScreen/EXSplashScreenService.h>
#import <UMCore/UMModuleRegistryProvider.h>

#import "BraintreeCore.h"

#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
```

**Comment by ananthauppangala** [comment]
If you are using Braintree v5 use the following line
`[BTAppContextSwitcher setReturnURLScheme:self.paymentsURLScheme];`
