### ISSUE TITLE
Add "all contributors"

### ISSUE THREAD

**Issue by vasylnahuliak** [ekreative/react-native-braintree#43]
https://github.com/all-contributors/all-contributors

**Comment by dakshsinghrathore** [comment]
Hey @vasylnahuliak I have a fairly good knowledge regarding this issue, would love to work on it, will create a PR soon.

**Comment by vasylnahuliak** [comment]
Done in https://github.com/ekreative/react-native-braintree/pull/61

**Comment by vasylnahuliak** [comment]
@dakshsinghrathore Please add some additional information, how feature work? I do not see any new changes.

**Comment by dakshsinghrathore** [comment]
Hey @vasylnahuliak, kindly refer to this https://allcontributors.org/docs/en/bot/usage .... hope it helps, if not will create demo tutorial on its usage and ping you.
