### ISSUE TITLE
Set up CI/CD for deploying on npm

### ISSUE THREAD

**Issue by vasylnahuliak** [ekreative/react-native-braintree#44]
Will be good to have automatic release without manual boring work

**Comment by georgioupanayiotis** [comment]
@vasylnahuliak can you assign this to me

**Comment by georgioupanayiotis** [comment]
Created the PR [here](https://github.com/ekreative/react-native-braintree/pull/47)

**Comment by vasylnahuliak** [comment]
Done in https://github.com/ekreative/react-native-braintree/pull/47
