### ISSUE TITLE
Add Native SDK versions in README

### ISSUE THREAD

**Issue by vasylnahuliak** [ekreative/react-native-braintree#52]
Add the table with Native SDK versions for all react-native-braintree releases with changed version 

For example:

| Package Version  | Android SDK | iOS SDK |
| ------------- | ------------- | ------------- |
| [1.0.0](https://github.com/ekreative/react-native-braintree/releases/tag/v1.0.0)  | x.y.z | x.y.z |

**Comment by ad-astra-per-ardua** [comment]
Would it be appropriate to extract the Android SDK from the build.gradle file, and due to the absence of Podfile.lock, alternatively fetch the iOS SDK from the packagelock.json under the section
```
"node_modules/@react-native-community/cli-platform-ios": {
      "version": "3.2.0",
      ...
    },
```
and then create a Python script to update the version in the main README.md at the top, and set up a workflow to commit and push each file whenever they are pushed?

**Comment by vasylnahuliak** [comment]
@d982h8st7 

These versions don't change often, so I guess this will be overengineering creating some script. For this issue need just create manual changes in README.

Thanks for the idea!

**Comment by ad-astra-per-ardua** [comment]
> @d982h8st7
> 
> These versions don't change often, so I guess this will be overengineering creating some script. For this issue need just create manual changes in README.
> 
> Thanks for the idea!

Then you just need table frame of each version on the top of main README.md?

**Comment by vasylnahuliak** [comment]
> > @d982h8st7
> 
> > 
> 
> > These versions don't change often, so I guess this will be overengineering creating some script. For this issue need just create manual changes in README.
> 
> > 
> 
> > Thanks for the idea!
> 
> 
> 
> Then you just need table frame of each version on the top of main README.md?

Yes, like in an example in the description. Also you can skip versions with the same numbers.

**Comment by ad-astra-per-ardua** [comment]
> > > @d982h8st7
> > 
> > 
> > > 
> > 
> > 
> > > These versions don't change often, so I guess this will be overengineering creating some script. For this issue need just create manual changes in README.
> > 
> > 
> > > 
> > 
> > 
> > > Thanks for the idea!
> > 
> > 
> > Then you just need table frame of each version on the top of main README.md?
> 
> Yes, like in an example in the description. Also you can skip versions with the same numbers.

Can i take this issue pls?

**Comment by d982h8st7** [comment]
# 1) 
![image](https://github.com/ekreative/react-native-braintree/assets/50827253/6dafd03b-3fce-410b-96c3-5575a242d558)
<hr>

# 2)

![image](https://github.com/ekreative/react-native-braintree/assets/50827253/3c2fd53b-77f5-4131-b5e5-78d55cf558a2)
<hr>

# 3)
![image](https://github.com/ekreative/react-native-braintree/assets/50827253/51e95a57-eabf-4305-bbd9-5b7fee3e2894)

<hr>

Which do you prefer among these? Or do you have any specific in mind? @vasylnahuliak

**Comment by vasylnahuliak** [comment]
Done in https://github.com/ekreative/react-native-braintree/pull/80
