### ISSUE TITLE
Add unit testing for JS files

### ISSUE THREAD

**Issue by vasylnahuliak** [ekreative/react-native-braintree#53]
Add unit testing for JS files

Add shared mocks (for example https://github.com/software-mansion/react-native-reanimated/blob/main/mock.js)

**Comment by AgentPrus** [comment]
@vasylnahuliak I'll handle this

**Comment by vasylnahuliak** [comment]
It seems there hasn't been any activity on this issue for a while. Closing it now, but don't hesitate to reopen it if needed.
