### ISSUE TITLE
Investigate rewrite Android part using Kotlin

### ISSUE THREAD

**Issue by vasylnahuliak** [ekreative/react-native-braintree#54]
The current android code base is written on Java. Will be good to fresh this code using the new android language standard.

**Comment by veruyuschiyateist** [comment]
hi

**Comment by Chlorine2** [comment]
+

**Comment by tihhan** [comment]
+

**Comment by maxix28** [comment]
!

**Comment by vasylnahuliak** [comment]
@veruyuschiyateist @Chlorine2 @tihhan @maxix28  according to [LOW OR NON CODE CONTRIBUTIONS ](https://hacktoberfest.com/participation/#pr-mr-details) you can create the pull request with your comments in markdown format in `docs` folder with "kotling-migration" filename for tracking your progress.

**Comment by vasylnahuliak** [comment]
It seems there hasn't been any activity on this issue for a while. Closing it now, but don't hesitate to reopen it if needed.
