### ISSUE TITLE
Add ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by vasylnahuliak** [ekreative/react-native-braintree#56]
Docs https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

**Comment by dakshsinghrathore** [comment]
Hey @vasylnahuliak would love to work on this issue, as I have some prior experience in resolving it, I would suggest to create issue forms instead, it will be more user friendly... something like this 👇🏽

**ISSUE BUTTONS**


![image](https://github.com/ekreative/react-native-braintree/assets/115932772/9cf9fb93-d09a-43f5-94ca-e8de1fd0ece7)


**ISSUE FORMS**


![image](https://github.com/ekreative/react-native-braintree/assets/115932772/860c6d06-79f1-4605-9fee-2aabadda0669)

**Comment by vasylnahuliak** [comment]
@dakshsinghrathore Cool idea, Thanks!

It's yours.

**Comment by vasylnahuliak** [comment]
Done in https://github.com/ekreative/react-native-braintree/pull/75
