### ISSUE TITLE
Add PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by vasylnahuliak** [ekreative/react-native-braintree#57]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by dakshsinghrathore** [comment]
Hey @vasylnahuliak would love to work on this issue, can you share the details you would like to add in the template, any specifics one should take care of ???

**Comment by vasylnahuliak** [comment]
@dakshsinghrathore Now, I do not have any special thing. I guess we need to start with a popular scenario. In the future, we will be detailing this.

Try to find a popular react-native library and take inspiration.

**Comment by dakshsinghrathore** [comment]
Got it @vasylnahuliak

**Comment by vasylnahuliak** [comment]
Done in https://github.com/ekreative/react-native-braintree/pull/76

Thanks!

**Comment by vasylnahuliak** [comment]
@dakshsinghrathore Could you fix lint errors? https://github.com/ekreative/react-native-braintree/actions/runs/6689733039/job/18173761098

**Comment by dakshsinghrathore** [comment]
@vasylnahuliak yeah sure, will create a PR soon
