### ISSUE TITLE
Add links in README

### ISSUE THREAD

**Issue by vasylnahuliak** [ekreative/react-native-braintree#60]
To increase the popularity of the library, add the following links to the documentation:
- https://reactnative.directory/?search=react-native-braintree
- https://reintech.io/blog/tutorial-for-react-developers-what-are-the-best-react-native-libraries-for-creating-mobile-payments
- https://reactnativeexample.com/a-react-native-interface-for-integrating-payments-using-braintree/
- https://www.npmjs.com/package/@ekreative/react-native-braintree

TODO:
- [x] come up with a name for the section
- [x]  add a minimal description

**Comment by Hollister009** [comment]
@vasylnahuliak can you assign this one to me?

**Comment by Hollister009** [comment]
- [x]  come up with a name for the section:
Useful links and resources

**Comment by Hollister009** [comment]
Create PR, please review: https://github.com/ekreative/react-native-braintree/pull/64

**Comment by vasylnahuliak** [comment]
Awesome!
