### ISSUE TITLE
Add Cache to CI/CD

### ISSUE THREAD

**Issue by AgentPrus** [ekreative/react-native-braintree#72]
## Problem
For now, CI/CD is working without a cache. So, each time it installs node_modules even if there are no changes made.

## Solution
There is a cache option in setup-node action so we can turn on it.

## Links
- [related issue](https://github.com/actions/setup-node/issues/819)
- setup-node action [docs](https://github.com/actions/setup-node#caching-global-packages-data)

**Comment by vasylnahuliak** [comment]
Thanks for the issue

**Comment by vasylnahuliak** [comment]
It seems there hasn't been any activity on this issue for a while. Closing it now, but don't hesitate to reopen it if needed.
