### ISSUE TITLE
Add branch name linter

### ISSUE THREAD

**Issue by vasylnahuliak** [ekreative/react-native-braintree#73]
Use a popular standard for config, for example https://danielkummer.github.io/git-flow-cheatsheet/index.uk_UA.html

Example tools:
- https://github.com/JsonMa/validate-branch-name
- https://www.npmjs.com/package/branch-name-lint

**Comment by ad-astra-per-ardua** [comment]
Hi, can i try this? @vasylnahuliak  :)

**Comment by vasylnahuliak** [comment]
@d982h8st7 Yes, please!

**Comment by ad-astra-per-ardua** [comment]
@vasylnahuliak Should i document the branch naming linting rules in the README? if yes, where should i put it?

**Comment by vasylnahuliak** [comment]
> Should i document the branch naming linting rules in the README? if yes, where should i put it?

In my opinion, we can avoid adding additional documentation because husky will be warned when you have a wrong branch name.

Done in https://github.com/ekreative/react-native-braintree/pull/77
