### ISSUE TITLE
Production steps to enable apple and google pay

### ISSUE THREAD

**Issue by manos2864** [ekreative/react-native-braintree#85]
### What's wrong with the existing documentation

In stage environment the apple pay and google pay is working but in production both of them are not. Can someone explain to me what else i should do to enable them; 
I have enable the options in my braintree panel and i have perform the steps for the ios  certification files.. 

Google play is throwing an OR_BIBED_11 error and apple pay is throwing an error unable to decrypt.

can someone help? maybe some instructions or links how to enable these payments?

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by vasylnahuliak** [comment]
It is not related to this library. Please, use the official support of Braintree for resolving this issue.
