### ISSUE TITLE
showPayPalModule of null

### ISSUE THREAD

**Issue by ashhusen97** [ekreative/react-native-braintree#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

TypeError: Cannot read property 'showPayPalModule' of null, js engine: hermes

got this issue in while import RNBraintree application is crashing 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by vasylnahuliak** [comment]
Do you use Expo?

Do you use install pods?

Do you build using Xcode?

**Comment by BigBam** [comment]
I am also encountered this issue, using Expo running in iOS simulator. I did not install pods or build with Xcode.

**Comment by vasylnahuliak** [comment]
This library does not support at Expo

https://github.com/ekreative/react-native-braintree/issues?q=is%3Aissue+is%3Aclosed+expo

**Comment by ashhusen97** [comment]
> Do you use Expo?
> 
> Do you use install pods?
> 
> Do you build using Xcode?

No I am not using expo its not even working for android emulator

**Comment by ashhusen97** [comment]
> This library does not support at Expo
> 
> https://github.com/ekreative/react-native-braintree/issues?q=is%3Aissue+is%3Aclosed+expo

I am using bare react native not expo its still showing this error p.s i am using android emulator

**Comment by vasylnahuliak** [comment]
@ashhusen97 Could you try to use the old version, for example, https://github.com/ekreative/react-native-braintree/releases/tag/v2.4.0 ?

**Comment by vasylnahuliak** [comment]
@ashhusen97 please attach the output from `npx react-native info`

**Comment by vasylnahuliak** [comment]
Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please feel free to create a new issue with up-to-date information.
